public class NewIdCardTestCntrlr 
 {

    public String Isize { get; set; }

    public String Csize { get; set; }

    public String Esize { get; set; }

    public String Rsize { get; set; }

    public String comsize { get; set; }

    public String Appsize { get; set; }

    public String Pensize { get; set; }

    public String getSubsize() {
        return null;
    }

   Public NewIdCardTestCntrlr()
    {
       
    }
 }